### ISSUE TITLE
Error running command just-files.refreshJustFiles

### ISSUE THREAD

**Issue by mrelemerson** [palaso0/just-files#1]
When I want to run it, I get the message:

Error running command just-files.refreshJustFiles: command 'just-files.refreshJustFiles' not found. This is likely caused by the extension that contributes just-files.refreshJustFiles.

i am using vscode on linux mint victoria

**Comment by palaso0** [comment]
Hi @mrelemerson, does it happened when you installed the extension? Or when you click on the refresh button? Are you able to add files to the JustFiles view?

**Comment by mrelemerson** [comment]
I just select a folder and click on "Add to Just Files" and as nothing is seen in the JUST FILES explorer I click on refresh and the message comes out: 

Error running command just-files.refreshJustFiles: command 'just-files.refreshJustFiles' not found. This is likely caused by the extension that contributes just-files.refreshJustFiles.

**Comment by palaso0** [comment]
Thanks! I'll take a look

**Comment by palaso0** [comment]
Hi, seems that the problem was: 

```
Activating extension 'palaso.just-files' failed: Cannot find module './classes/justFiles'
Require stack:
- /home/----/.vscode/extensions/palaso.just-files-1.0.1/out/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
- .
```

It was because the file `JustFiles.ts` was renamed to `justFiles.ts`, but in the `out` folder generated it was still as `JustFiles.js`. And the main file `extension.js` was looking for `./classes/justFiles` but using the file 'JustFiles.js'. There were no problems for Windows neighter MacOs, but seems in your SO `extension.js` was lookin for the exact `./classes/justFiles`.
 
I compiled the project again and now the `out` folder has the correct  file`justFiles.js`. And seems it its working fine now for Linux Mint 20:

<img width="1440" alt="Captura de Pantalla 2023-08-28 a la(s) 13 41 33" src="https://github.com/palaso0/just-files/assets/30333035/e9de63b9-feb7-40a5-ba00-9e370879d2ba">

Could you please install/update the extension again and verify it is working fine?
The fix was realease in v1.0.2

**Comment by mrelemerson** [comment]
Already works!!!, excellent extension

**Comment by palaso0** [comment]
Great!! Sorry for the inconveniences and hope you enjoy the extension.
Thanks for detect this problem.
